export const products = [
    // --- Limpeza ---
    {
        id: 1,
        name: "Detergente Concentrado 5L",
        category: "Limpeza",
        price: 35.90,
        unit: "gl",
        image: "https://images.unsplash.com/photo-1585232004423-2848c51f47f4?auto=format&fit=crop&q=80&w=500",
        description: "Excelente rendimento, remove gorduras difíceis com facilidade. Ideal para uso profissional e doméstico.",
    },
    {
        id: 2,
        name: "Kit Vassoura e Pá",
        category: "Limpeza",
        price: 49.90,
        unit: "un",
        image: "https://images.unsplash.com/photo-1581567104642-1c25fb18c5e0?auto=format&fit=crop&q=80&w=500",
        description: "Vassoura de cerdas macias com pá coletora de alta resistência. Cabo ergonômico.",
    },
    {
        id: 3,
        name: "Mop Giratório Completo",
        category: "Limpeza",
        price: 129.90,
        unit: "un",
        image: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&q=80&w=500",
        description: "Balde com centrífuga em inox e cabo ajustável. Facilita a limpeza de pisos sem contato com a água suja.",
    },
    {
        id: 4,
        name: "Esponja Multiuso (Pacote com 4)",
        category: "Limpeza",
        price: 12.00,
        unit: "pc",
        image: "https://images.unsplash.com/photo-1583947215259-38e31be8751f?auto=format&fit=crop&q=80&w=500",
        description: "Dupla face, não risca. Durabilidade superior para louças e superfícies delicadas.",
    },
    {
        id: 5,
        name: "Desinfetante Lavanda 2L",
        category: "Limpeza",
        price: 18.50,
        unit: "uni",
        image: "https://images.unsplash.com/photo-1612198188060-c7c2a3b66eae?auto=format&fit=crop&q=80&w=500",
        description: "Fragrância duradoura e ação germicida. Elimina 99,9% das bactérias.",
    },

    // --- Utensílios ---
    {
        id: 6,
        name: "Conjunto de Potes Herméticos",
        category: "Utensílios",
        price: 89.90,
        unit: "jg",
        image: "https://images.unsplash.com/photo-1610701596007-11502861dcfa?auto=format&fit=crop&q=80&w=500",
        description: "Kit com 5 potes de tamanhos variados. Vedação em silicone que mantém os alimentos frescos por mais tempo.",
    },
    {
        id: 7,
        name: "Lixeira Inox com Pedal 5L",
        category: "Utensílios",
        price: 75.00,
        unit: "un",
        image: "https://images.unsplash.com/photo-1593060699252-8c5fe155a5b5?auto=format&fit=crop&q=80&w=500",
        description: "Design elegante e higiênico. Balde interno removível para facilitar a limpeza.",
    },
    {
        id: 8,
        name: "Escorredor de Louça Duplo",
        category: "Utensílios",
        price: 98.00,
        unit: "un",
        image: "https://images.unsplash.com/photo-1581622558663-b2e33377dfb2?auto=format&fit=crop&q=80&w=500",
        description: "Capacidade para 16 pratos, copos e talheres. Acabamento cromado resistente à corrosão.",
    },

    // --- Organização (Incluindo antigos itens de lavanderia) ---
    {
        id: 9,
        name: "Cesto de Roupa Dobrável",
        category: "Organização",
        price: 55.90,
        unit: "un",
        image: "https://images.unsplash.com/photo-1562251181-c1f4a434c442?auto=format&fit=crop&q=80&w=500",
        description: "Prático e compacto. Material respirável que evita odores nas roupas sujas.",
    },
    {
        id: 10,
        name: "Varal de Chão com Abas",
        category: "Organização",
        price: 110.00,
        unit: "un",
        image: "https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&q=80&w=500",
        description: "Estrutura robusta em alumínio. Abas laterais que aumentam a capacidade de secagem.",
    },
    {
        id: 11,
        name: "Organizador de Gavetas",
        category: "Organização",
        price: 29.90,
        unit: "un",
        image: "https://images.unsplash.com/photo-1540574163026-643ea20ade25?auto=format&fit=crop&q=80&w=500",
        description: "Ideal para talheres, roupas íntimas ou materiais de escritório. Modular e ajustável.",
    },
    {
        id: 12,
        name: "Dispenser de Sabonete Líquido",
        category: "Organização",
        price: 45.00,
        unit: "un",
        image: "https://images.unsplash.com/photo-1584305574647-0cc949a2bb9f?auto=format&fit=crop&q=80&w=500",
        description: "Elegância para seu banheiro ou lavabo. Válvula pump de alta durabilidade.",
    },
    // --- Automotivo (Novos) ---
    {
        id: 13,
        name: "Shampoo Automotivo com Cera 500ml",
        category: "Automotivo",
        price: 24.90,
        unit: "un",
        image: "https://images.unsplash.com/photo-1601362840469-51e4d8d58785?auto=format&fit=crop&q=80&w=500",
        description: "Limpa e protege a pintura do seu carro. Brilho intenso e proteção duradoura.",
    },
    {
        id: 14,
        name: "Esponja para Lavar Carro",
        category: "Automotivo",
        price: 15.00,
        unit: "un",
        image: "https://images.unsplash.com/photo-1507138451611-31ff74a91a84?auto=format&fit=crop&q=80&w=500",
        description: "Maciez que não risca a lataria. Alta absorção de espuma.",
    }
];

export const CATEGORIES = ["Todos", "Limpeza", "Utensílios", "Organização", "Automotivo"];
